/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.Avance1_Grupo2;

/**
 *
 * @author hhern
 */
public class VentElimEspec extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentElimEspec
     */
    public VentElimEspec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Especialidades = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        placaBusc = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        finalLabel = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Eliminar clientes por especialidad");

        Especialidades.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Especialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mecanica Basica", "Mecanica automotores diesel", "Mecanica automotores gasolina", "Mecanica automotores electricos", "Mecanica de maquinaria pesada", "Mecanica de motos" }));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Buscar placa a eliminar:");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        placaBusc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(finalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(34, 34, 34)
                                .addComponent(placaBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(Especialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Especialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(placaBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(31, 31, 31))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica Basica")) {
            placaBusc.removeAllItems();
            for (int i = 0; i < MecanicaBasica.getMecBasica().size(); i++) {
                placaBusc.addItem(MecanicaBasica.getMecBasica().get(i).getPlaca());
            }
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores diesel")) {
            placaBusc.removeAllItems();
            for (int i = 0; i < MecanicaDiesel.getMecDiesel().size(); i++) {
                placaBusc.addItem(MecanicaDiesel.getMecDiesel().get(i).getPlaca());
            }
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores gasolina")) {
            placaBusc.removeAllItems();
            for (int i = 0; i < MecanicaGasolina.getMecGasolina().size(); i++) {
                placaBusc.addItem(MecanicaGasolina.getMecGasolina().get(i).getPlaca());
            }
           
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores electricos")) {
            placaBusc.removeAllItems();
            for (int i = 0; i < MecanicaElectricos.getMecElectricos().size(); i++) {
                placaBusc.addItem(MecanicaElectricos.getMecElectricos().get(i).getPlaca());
            }
           
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica de maquinaria pesada")) {
            placaBusc.removeAllItems();
            for (int i = 0; i < MecanicaPesada.getMecPesada().size(); i++) {
                placaBusc.addItem(MecanicaPesada.getMecPesada().get(i).getPlaca());
            }
            
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica de motos")) {
            placaBusc.removeAllItems();
            for (int i = 0; i < MecanicaMotos.getMecMotos().size(); i++) {
                placaBusc.addItem(MecanicaMotos.getMecMotos().get(i).getPlaca());
            }
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica Basica")) {
            for (int i = 0; i < MecanicaBasica.getMecBasica().size(); i++) {
                if (placaBusc.getSelectedItem().toString().equalsIgnoreCase(MecanicaBasica.getMecBasica().get(i).getPlaca())) {
                    MecanicaBasica.getMecBasica().remove(i);
                }
            }
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores diesel")) {
            for (int i = 0; i < MecanicaDiesel.getMecDiesel().size(); i++) {
                if (placaBusc.getSelectedItem().toString().equalsIgnoreCase(MecanicaDiesel.getMecDiesel().get(i).getPlaca())) {
                    MecanicaDiesel.getMecDiesel().remove(i);
                }
            }
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores gasolina")) {
            for (int i = 0; i < MecanicaGasolina.getMecGasolina().size(); i++) {
                if (placaBusc.getSelectedItem().toString().equalsIgnoreCase(MecanicaGasolina.getMecGasolina().get(i).getPlaca())) {
                    MecanicaGasolina.getMecGasolina().remove(i);
                }
            }
           
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores electricos")) {
            for (int i = 0; i < MecanicaElectricos.getMecElectricos().size(); i++) {
                if (placaBusc.getSelectedItem().toString().equalsIgnoreCase(MecanicaElectricos.getMecElectricos().get(i).getPlaca())) {
                    MecanicaElectricos.getMecElectricos().remove(i);
                }
            }
           
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica de maquinaria pesada")) {
            for (int i = 0; i < MecanicaPesada.getMecPesada().size(); i++) {
                if (placaBusc.getSelectedItem().toString().equalsIgnoreCase(MecanicaPesada.getMecPesada().get(i).getPlaca())) {
                    MecanicaPesada.getMecPesada().remove(i);
                }
            }
            
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica de motos")) {
            for (int i = 0; i < MecanicaMotos.getMecMotos().size(); i++) {
                if (placaBusc.getSelectedItem().toString().equalsIgnoreCase(MecanicaMotos.getMecMotos().get(i).getPlaca())) {
                    MecanicaMotos.getMecMotos().remove(i);
                }
            }
           
        }
        placaBusc.removeAllItems();
        finalLabel.setText("Eliminado Correctamente");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Especialidades;
    private javax.swing.JLabel finalLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> placaBusc;
    // End of variables declaration//GEN-END:variables
}
