/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.Avance1_Grupo2;

/**
 *
 * @author hhern
 */
public class VentModEspec extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentModEspec
     */
    public VentModEspec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        especialidad = new javax.swing.JComboBox<>();
        placaBusc = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textNew = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        finalLabel = new javax.swing.JLabel();
        valorMod = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Modificar especialidades");

        especialidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mecanica Basica", "Mecanica automotores diesel", "Mecanica automotores gasolina", "Mecanica automotores electricos", "Mecanica de maquinaria pesada", "Mecanica de motos" }));

        placaBusc.setEditable(true);
        placaBusc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Buscar placa a eliminar:");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nuevo valor:");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        finalLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        valorMod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        valorMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre de cliente", "Placa", "Nombre de mecanico", "Especialidad", "Sub especialidad", "Valor de reparacion" }));
        valorMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorModActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Valor a modificar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(placaBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNew, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(finalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(75, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(placaBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(finalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorModActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (especialidad.getSelectedItem().toString().equalsIgnoreCase("Mecanica Basica")) {
            placaBusc.removeAllItems();
            for (int i = 0; i < MecanicaBasica.getMecBasica().size(); i++) {
                placaBusc.addItem(MecanicaBasica.getMecBasica().get(i).getPlaca());
            }
        } else if (especialidad.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores diesel")) {
            placaBusc.removeAllItems();
            for (int i = 0; i < MecanicaDiesel.getMecDiesel().size(); i++) {
                placaBusc.addItem(MecanicaDiesel.getMecDiesel().get(i).getPlaca());
            }
        } else if (especialidad.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores gasolina")) {
            placaBusc.removeAllItems();
            for (int i = 0; i < MecanicaGasolina.getMecGasolina().size(); i++) {
                placaBusc.addItem(MecanicaGasolina.getMecGasolina().get(i).getPlaca());
            }

        } else if (especialidad.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores electricos")) {
            placaBusc.removeAllItems();
            for (int i = 0; i < MecanicaElectricos.getMecElectricos().size(); i++) {
                placaBusc.addItem(MecanicaElectricos.getMecElectricos().get(i).getPlaca());
            }

        } else if (especialidad.getSelectedItem().toString().equalsIgnoreCase("Mecanica de maquinaria pesada")) {
            placaBusc.removeAllItems();
            for (int i = 0; i < MecanicaPesada.getMecPesada().size(); i++) {
                placaBusc.addItem(MecanicaPesada.getMecPesada().get(i).getPlaca());
            }

        } else if (especialidad.getSelectedItem().toString().equalsIgnoreCase("Mecanica de motos")) {
            placaBusc.removeAllItems();
            for (int i = 0; i < MecanicaMotos.getMecMotos().size(); i++) {
                placaBusc.addItem(MecanicaMotos.getMecMotos().get(i).getPlaca());
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (especialidad.getSelectedItem().toString().equalsIgnoreCase("Mecanica Basica")) {
            for (int i = 0; i < MecanicaBasica.getMecBasica().size(); i++) {
                if (placaBusc.getSelectedItem().toString().equalsIgnoreCase(MecanicaBasica.getMecBasica().get(i).getPlaca())) {
                    if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Nombre de cliente")) {
                        MecanicaBasica.getMecBasica().get(i).setNombreCliente(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Placa")) {
                        MecanicaBasica.getMecBasica().get(i).setPlaca(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Nombre de mecanico")) {
                        MecanicaBasica.getMecBasica().get(i).setNombreMec(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Especialidad")) {
                        MecanicaBasica.getMecBasica().get(i).setEspecialidad(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Sub especialidad")) {
                        MecanicaBasica.getMecBasica().get(i).setSubEspec(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Valor de reparacion")) {
                        MecanicaBasica.getMecBasica().get(i).setValorRep(Integer.parseInt(textNew.getText()));
                    }
                }
            }
        } else if (especialidad.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores diesel")) {
            for (int i = 0; i < MecanicaDiesel.getMecDiesel().size(); i++) {
                if (placaBusc.getSelectedItem().toString().equalsIgnoreCase(MecanicaDiesel.getMecDiesel().get(i).getPlaca())) {
                    if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Nombre de cliente")) {
                        MecanicaDiesel.getMecDiesel().get(i).setNombreCliente(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Placa")) {
                        MecanicaDiesel.getMecDiesel().get(i).setPlaca(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Nombre de mecanico")) {
                        MecanicaDiesel.getMecDiesel().get(i).setNombreMec(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Especialidad")) {
                        MecanicaDiesel.getMecDiesel().get(i).setEspecialidad(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Sub especialidad")) {
                        MecanicaDiesel.getMecDiesel().get(i).setSubEspec(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Valor de reparacion")) {
                        MecanicaDiesel.getMecDiesel().get(i).setValorRep(Integer.parseInt(textNew.getText()));
                    }
                }
            }
        } else if (especialidad.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores gasolina")) {
            for (int i = 0; i < MecanicaGasolina.getMecGasolina().size(); i++) {
                if (placaBusc.getSelectedItem().toString().equalsIgnoreCase(MecanicaGasolina.getMecGasolina().get(i).getPlaca())) {
                    if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Nombre de cliente")) {
                        MecanicaGasolina.getMecGasolina().get(i).setNombreCliente(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Placa")) {
                        MecanicaGasolina.getMecGasolina().get(i).setPlaca(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Nombre de mecanico")) {
                        MecanicaGasolina.getMecGasolina().get(i).setNombreMec(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Especialidad")) {
                        MecanicaGasolina.getMecGasolina().get(i).setEspecialidad(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Sub especialidad")) {
                        MecanicaGasolina.getMecGasolina().get(i).setSubEspec(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Valor de reparacion")) {
                        MecanicaGasolina.getMecGasolina().get(i).setValorRep(Integer.parseInt(textNew.getText()));
                    }
                }
            }
        } else if (especialidad.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores electricos")) {
            for (int i = 0; i < MecanicaElectricos.getMecElectricos().size(); i++) {
                if (placaBusc.getSelectedItem().toString().equalsIgnoreCase(MecanicaElectricos.getMecElectricos().get(i).getPlaca())) {
                    if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Nombre de cliente")) {
                        MecanicaElectricos.getMecElectricos().get(i).setNombreCliente(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Placa")) {
                        MecanicaElectricos.getMecElectricos().get(i).setPlaca(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Nombre de mecanico")) {
                        MecanicaElectricos.getMecElectricos().get(i).setNombreMec(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Especialidad")) {
                        MecanicaElectricos.getMecElectricos().get(i).setEspecialidad(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Sub especialidad")) {
                        MecanicaElectricos.getMecElectricos().get(i).setSubEspec(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Valor de reparacion")) {
                        MecanicaElectricos.getMecElectricos().get(i).setValorRep(Integer.parseInt(textNew.getText()));
                    }
                }
            }
        } else if (especialidad.getSelectedItem().toString().equalsIgnoreCase("Mecanica de maquinaria pesada")) {
            for (int i = 0; i < MecanicaPesada.getMecPesada().size(); i++) {
                if (placaBusc.getSelectedItem().toString().equalsIgnoreCase(MecanicaPesada.getMecPesada().get(i).getPlaca())) {
                    if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Nombre de cliente")) {
                        MecanicaPesada.getMecPesada().get(i).setNombreCliente(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Placa")) {
                        MecanicaPesada.getMecPesada().get(i).setPlaca(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Nombre de mecanico")) {
                        MecanicaPesada.getMecPesada().get(i).setNombreMec(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Especialidad")) {
                        MecanicaPesada.getMecPesada().get(i).setEspecialidad(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Sub especialidad")) {
                        MecanicaPesada.getMecPesada().get(i).setSubEspec(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Valor de reparacion")) {
                        MecanicaPesada.getMecPesada().get(i).setValorRep(Integer.parseInt(textNew.getText()));
                    }
                }
            }
        } else if (especialidad.getSelectedItem().toString().equalsIgnoreCase("Mecanica de motos")) {
            for (int i = 0; i < MecanicaMotos.getMecMotos().size(); i++) {
                if (placaBusc.getSelectedItem().toString().equalsIgnoreCase(MecanicaMotos.getMecMotos().get(i).getPlaca())) {
                    if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Nombre de cliente")) {
                        MecanicaMotos.getMecMotos().get(i).setNombreCliente(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Placa")) {
                        MecanicaMotos.getMecMotos().get(i).setPlaca(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Nombre de mecanico")) {
                        MecanicaMotos.getMecMotos().get(i).setNombreMec(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Especialidad")) {
                        MecanicaMotos.getMecMotos().get(i).setEspecialidad(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Sub especialidad")) {
                        MecanicaMotos.getMecMotos().get(i).setSubEspec(textNew.getText());
                    } else if (valorMod.getSelectedItem().toString().equalsIgnoreCase("Valor de reparacion")) {
                        MecanicaMotos.getMecMotos().get(i).setValorRep(Integer.parseInt(textNew.getText()));
                    }
                }
            }
        }
        placaBusc.removeAllItems();
        textNew.setText("");
        finalLabel.setText("Se ha modificado correctamente");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> especialidad;
    private javax.swing.JLabel finalLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> placaBusc;
    private javax.swing.JTextField textNew;
    private javax.swing.JComboBox<String> valorMod;
    // End of variables declaration//GEN-END:variables
}
