/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.Avance1_Grupo2;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Melani
 */
public class Factura extends javax.swing.JInternalFrame {

    DefaultTableModel model = new DefaultTableModel();

    public Factura() {
        initComponents();
        tablaPro.setModel(model);
        String titu[] = {"Servicio", "Precio", "Cantidad", "Importe"};
        model.setColumnIdentifiers(titu);
        tablaPro.getColumnModel().getColumn(0).setPreferredWidth(200);
    }

    /**
     * Creates new form Factura
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCan = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        Clientes = new javax.swing.JComboBox();
        Especialidades = new javax.swing.JComboBox();
        servBusc = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        sub = new javax.swing.JComboBox();
        jbutton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPro = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        subtotal = new javax.swing.JLabel();
        iva = new javax.swing.JLabel();
        tot = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Factura");

        jLabel2.setText("Cliente");

        jLabel3.setText("Especialidad");

        jLabel4.setText("Servicios");

        txtPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad");

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        Clientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[Seleccionar]" }));
        Clientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ClientesItemStateChanged(evt);
            }
        });
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });

        Especialidades.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mecanica Basica", "Mecanica automotores diesel", "Mecanica automotores gasolina", "Mecanica automotores electricos", "Mecanica de maquinaria pesada", "Mecanica de motos" }));
        Especialidades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EspecialidadesItemStateChanged(evt);
            }
        });
        Especialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecialidadesActionPerformed(evt);
            }
        });

        servBusc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                servBuscItemStateChanged(evt);
            }
        });
        servBusc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servBuscActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sub.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                subItemStateChanged(evt);
            }
        });
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        jbutton.setText("Agregar Subservicio");
        jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Precio a buscar:");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Clientes, 0, 178, Short.MAX_VALUE)
                            .addComponent(Especialidades, 0, 1, Short.MAX_VALUE)
                            .addComponent(servBusc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 17, Short.MAX_VALUE)
                                .addComponent(jbutton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(agregar)
                                .addGap(18, 18, 18)
                                .addComponent(eliminar))
                            .addComponent(txtPre, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Especialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbutton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(txtPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregar)
                            .addComponent(eliminar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("# Factura");

        jLabel11.setText("001-2500-8956");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPro);

        subtotal.setText("00.00");

        iva.setText("00.00");

        tot.setText("00.00");

        jLabel9.setText("Total");

        jLabel8.setText("IVA");

        jLabel7.setText("SubTotal");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(subtotal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iva))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(tot))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotal)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iva)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tot)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreActionPerformed

    private double redondear(double num) {
        return Math.rint(num * 100) / 100;
    }

    private void calcularTotal() {
        double suma = 0, IVA, total;
        for (int i = 0; i < tablaPro.getRowCount(); i++) {
            suma = suma + Double.parseDouble(model.getValueAt(i, 3).toString());
        }
        suma = redondear(suma);
        subtotal.setText(String.valueOf(suma));
        IVA = 0.13 * suma;
        IVA = redondear(IVA);
        total = suma * 1.13;
        total = redondear(total);
        iva.setText(String.valueOf(IVA));
        tot.setText(String.valueOf(total));

    }

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        String rowData[] = new String[5];
        rowData[0] = servBusc.getSelectedItem().toString();
        rowData[1] = txtPre.getText();
        rowData[2] = txtCan.getText();
        Double imp = Double.parseDouble(rowData[1]) * Double.parseDouble(rowData[2]);
        imp = redondear(imp);
        rowData[3] = imp.toString();
        model.addRow(rowData);
        calcularTotal();

    }//GEN-LAST:event_agregarActionPerformed

    private void eliminar() {
        int fil;
        if (model.getRowCount() > 0) {
            if (tablaPro.getSelectedRow() != -1) {
                fil = tablaPro.getSelectedRow();
                model.removeRow(fil);
                calcularTotal();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione Una Fila");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay Filas en la Tabla");
        }
    }
    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_eliminarActionPerformed

    private void ClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ClientesItemStateChanged

    }//GEN-LAST:event_ClientesItemStateChanged

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
   
    }//GEN-LAST:event_ClientesActionPerformed

    private void EspecialidadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EspecialidadesItemStateChanged

    }//GEN-LAST:event_EspecialidadesItemStateChanged

    private void EspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialidadesActionPerformed

    }//GEN-LAST:event_EspecialidadesActionPerformed

    private void servBuscItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_servBuscItemStateChanged
        

    }//GEN-LAST:event_servBuscItemStateChanged

    private void servBuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servBuscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servBuscActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*Especialidad Mecanica Básica, servicios "Cambio de aceite y filtros",
        "Cambio de bujias", "Cambio de llantas", "Revision de frenos", "Revision de luces"*/

        if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica Basica")) {
            servBusc.removeAllItems();
            String[] newItems = {"Cambio de aceite y filtros", "Cambio de bujias", "Cambio de llantas", "Revision de frenos", "Revision de luces"};
            servBusc.setModel(new DefaultComboBoxModel<>(newItems));
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores diesel")) {
            servBusc.removeAllItems();
            String[] newItems = {"Revision de motor", "Tune up", "Desgastes mecanicos", "Sistemas electricos"};
            servBusc.setModel(new DefaultComboBoxModel<>(newItems));
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores gasolina")) {
            servBusc.removeAllItems();
            String[] newItems = {"Revision de motor", "Tune up", "Desgaste mecanico", "Sistemas electricos", "Cambio de roles", "Cambio de caja de cambios"};
            servBusc.setModel(new DefaultComboBoxModel<>(newItems));
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores electricos")) {
            servBusc.removeAllItems();
            String[] newItems = {"Sistema electrico y auxiliares", "Bateria", "Revision de frenos", "Cambio de roles"};
            servBusc.setModel(new DefaultComboBoxModel<>(newItems));
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica de maquinaria pesada")) {
            servBusc.removeAllItems();
            String[] newItems = {"Mantenimientos", "Reparacion", "Transmisiones", "Propulsion", "Electrico", "Chasis"};
            servBusc.setModel(new DefaultComboBoxModel<>(newItems));
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica de motos")) {
            servBusc.removeAllItems();
            String[] newItems = {"Diagnosticar", "Reparar componentes", "Sistema de lubricación y refrigeración", "Sistema de combustible", "Sistema de encendido", "Sistema de frenos", "Sistema de dirección", "Sistema de suspensión", "Transmisión", "Carga eléctrica"};
            servBusc.setModel(new DefaultComboBoxModel<>(newItems));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void subItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_subItemStateChanged
        
    }//GEN-LAST:event_subItemStateChanged

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subActionPerformed

    private void jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonActionPerformed
        /*Subservicios de Mecanica Básica y las otras especialidades*/
        if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica Basica")) {
            if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Cambio de aceite y filtros")) {
                sub.removeAllItems();
                String[] newItems = {"Motor", "Caja", "Hidraulico"};
                sub.setModel(new DefaultComboBoxModel<>(newItems));

            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Cambio de llantas")) {
                sub.removeAllItems();
                String[] newItems = {"Llantas nuevas", "Balanceo", "Tramado"};
                sub.setModel(new DefaultComboBoxModel<>(newItems));
            } else {
                sub.removeAllItems();
            }
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores diesel")) {
            sub.removeAllItems();
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores gasolina")) {
            if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Cambio de caja de cambios")) {
                sub.removeAllItems();
                String[] newItems = {"Caja manual", "Caja automatica"};
                sub.setModel(new DefaultComboBoxModel<>(newItems));
            } else {
                sub.removeAllItems();
            }
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores electricos")) {
            sub.removeAllItems();
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica de maquinaria pesada")) {
            sub.removeAllItems();
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica de motos")) {
            sub.removeAllItems();
        }
    }//GEN-LAST:event_jbuttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            Clientes.removeAllItems();
        for (int i = 0; i < Vehiculos.getAutos().size(); i++) {
            Clientes.addItem(Vehiculos.getAutos().get(i).getNombre());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica Basica")) {
            if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Cambio de aceite y filtros")) {
                if (sub.getSelectedItem().toString().equalsIgnoreCase("Motor")) {
                    txtPre.setText("35000");
                } else if (sub.getSelectedItem().toString().equalsIgnoreCase("Caja")) {
                    txtPre.setText("25000");
                } else if (sub.getSelectedItem().toString().equalsIgnoreCase("Hidraulico")) {
                    txtPre.setText("20000");
                }
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Cambio de bujias")) {
                txtPre.setText("40000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Cambio de llantas")) {
                if (sub.getSelectedItem().toString().equalsIgnoreCase("Llantas nuevas")) {
                    txtPre.setText("230000");
                } else if (sub.getSelectedItem().toString().equalsIgnoreCase("Balanceo")) {
                    txtPre.setText("23000");
                } else if (sub.getSelectedItem().toString().equalsIgnoreCase("Tramado")) {
                    txtPre.setText("23000");
                }
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Revision de frenos")) {
                txtPre.setText("46000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Revision de luces")) {
                txtPre.setText("50000");
            }
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores diesel")) {
            if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Revision de motor")) {
                txtPre.setText("60000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Tune up")) {
                txtPre.setText("100000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Desgastes mecanicos")) {
                txtPre.setText("200000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Sistemas electricos")) {
                txtPre.setText("80000");
            }
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores gasolina")) {
            if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Revision de motor")) {
                txtPre.setText("60000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Tune up")) {
                txtPre.setText("40000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Desgaste mecanico")) {
                txtPre.setText("40000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Sistemas electricos")) {
                txtPre.setText("76000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Cambio de roles")) {
                txtPre.setText("50000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Cambio de caja de cambios")) {
                if (sub.getSelectedItem().toString().equalsIgnoreCase("Caja manual")) {
                    txtPre.setText("100000");
                }else if (sub.getSelectedItem().toString().equalsIgnoreCase("Caja automatica")){
                    txtPre.setText("100000");
                }
            }
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores electricos")) {
            if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Sistema electrico y auxiliares")) {
                txtPre.setText("40000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Bateria")) {
                txtPre.setText("40000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Revision de frenos")) {
                txtPre.setText("46000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Cambio de roles")) {
                txtPre.setText("50000");
            }
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica de maquinaria pesada")) {
            if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Mantenimientos")) {
                txtPre.setText("140000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Reparacion")) {
                txtPre.setText("400000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Transmisiones")) {
                txtPre.setText("300000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Propulsion")) {
                txtPre.setText("460000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Electrico")) {
                txtPre.setText("100000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Chasis")) {
                txtPre.setText("150000");
            }
        } else if (Especialidades.getSelectedItem().toString().equalsIgnoreCase("Mecanica de motos")) {
            if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Diagnosticar")) {
                txtPre.setText("10000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Reparar componentes")) {
                txtPre.setText("40000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Sistema de lubricación y refrigeración")) {
                txtPre.setText("20000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Sistema de combustible")) {
                txtPre.setText("25000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Sistema de encendido")) {
                txtPre.setText("10000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Sistema de frenos")) {
                txtPre.setText("10000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Sistema de dirección")) {
                txtPre.setText("15000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Sistema de suspensión")) {
                txtPre.setText("10000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Transmisión")) {
                txtPre.setText("30000");
            } else if (servBusc.getSelectedItem().toString().equalsIgnoreCase("Carga eléctrica")) {
                txtPre.setText("25000");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Clientes;
    private javax.swing.JComboBox Especialidades;
    private javax.swing.JButton agregar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel iva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbutton;
    private javax.swing.JComboBox servBusc;
    private javax.swing.JComboBox sub;
    private javax.swing.JLabel subtotal;
    private javax.swing.JTable tablaPro;
    private javax.swing.JLabel tot;
    private javax.swing.JTextField txtCan;
    private javax.swing.JTextField txtPre;
    // End of variables declaration//GEN-END:variables
}
