/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.Avance1_Grupo2;

/**
 *
 * @author hhern
 */
public class VentElimEmple extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentElimEmple
     */
    public VentElimEmple() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseEspec = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        labelFinal = new javax.swing.JLabel();
        ident = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Eliminar Empleado");

        chooseEspec.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chooseEspec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mecanica Basica", "Mecanica automotores diesel", "Mecanica automotores gasolina", "Mecanica automotores electricos", "Mecanica de maquinaria pesada", "Mecanica de motos" }));
        chooseEspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseEspecActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ident.setEditable(true);
        ident.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Buscar Identificacion a eliminar:");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chooseEspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(65, 65, 65)
                            .addComponent(ident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(chooseEspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(labelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (chooseEspec.getSelectedItem().toString().equalsIgnoreCase("Mecanica Basica")) {
            for (int i = 0; i < Mecanicos.getMecBasica().size(); i++) {
                if (ident.getSelectedItem().toString().equalsIgnoreCase(String.valueOf(Mecanicos.getMecBasica().get(i).getCedula()))) {
                    Mecanicos.getMecBasica().remove(i);
                }
            }
        } else if (chooseEspec.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores diesel")) {
            for (int i = 0; i < Mecanicos.getMecDiesel().size(); i++) {
                if (ident.getSelectedItem().toString().equalsIgnoreCase(String.valueOf(Mecanicos.getMecDiesel().get(i).getCedula()))) {
                    Mecanicos.getMecDiesel().remove(i);
                }
            }
        } else if (chooseEspec.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores gasolina")) {
            for (int i = 0; i < Mecanicos.getMecGasolina().size(); i++) {
                if (ident.getSelectedItem().toString().equalsIgnoreCase(String.valueOf(Mecanicos.getMecGasolina().get(i).getCedula()))) {
                    Mecanicos.getMecGasolina().remove(i);
                }
            }
        } else if (chooseEspec.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores electricos")) {
            for (int i = 0; i < Mecanicos.getMecElectricos().size(); i++) {
                if (ident.getSelectedItem().toString().equalsIgnoreCase(String.valueOf(Mecanicos.getMecElectricos().get(i).getCedula()))) {
                    Mecanicos.getMecElectricos().remove(i);
                }
            }
        } else if (chooseEspec.getSelectedItem().toString().equalsIgnoreCase("Mecanica de maquinaria pesada")) {
            for (int i = 0; i < Mecanicos.getMecPesada().size(); i++) {
                if (ident.getSelectedItem().toString().equalsIgnoreCase(String.valueOf(Mecanicos.getMecPesada().get(i).getCedula()))) {
                    Mecanicos.getMecPesada().remove(i);
                }
            }
        } else if (chooseEspec.getSelectedItem().toString().equalsIgnoreCase("Mecanica de motos")) {
            for (int i = 0; i < Mecanicos.getMecMotos().size(); i++) {
                if (ident.getSelectedItem().toString().equalsIgnoreCase(String.valueOf(Mecanicos.getMecMotos().get(i).getCedula()))) {
                    Mecanicos.getMecMotos().remove(i);
                }
            }
        }
        ident.removeAllItems();
        labelFinal.setText("Empleado eliminado correctamente");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chooseEspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseEspecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseEspecActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (chooseEspec.getSelectedItem().toString().equalsIgnoreCase("Mecanica Basica")) {
            ident.removeAllItems();
            for (int i = 0; i < Mecanicos.getMecBasica().size(); i++) {
                ident.addItem(String.valueOf(Mecanicos.getMecBasica().get(i).getCedula()));
            }
        } else if (chooseEspec.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores diesel")) {
            ident.removeAllItems();
            for (int i = 0; i < Mecanicos.getMecDiesel().size(); i++) {
                ident.addItem(String.valueOf(Mecanicos.getMecDiesel().get(i).getCedula()));
            }
        } else if (chooseEspec.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores gasolina")) {
            ident.removeAllItems();
            for (int i = 0; i < Mecanicos.getMecGasolina().size(); i++) {
                ident.addItem(String.valueOf(Mecanicos.getMecGasolina().get(i).getCedula()));
            }
        } else if (chooseEspec.getSelectedItem().toString().equalsIgnoreCase("Mecanica automotores electricos")) {
            ident.removeAllItems();
            for (int i = 0; i < Mecanicos.getMecElectricos().size(); i++) {
                ident.addItem(String.valueOf(Mecanicos.getMecElectricos().get(i).getCedula()));
            }
        } else if (chooseEspec.getSelectedItem().toString().equalsIgnoreCase("Mecanica de maquinaria pesada")) {
            ident.removeAllItems();
            for (int i = 0; i < Mecanicos.getMecPesada().size(); i++) {
                ident.addItem(String.valueOf(Mecanicos.getMecPesada().get(i).getCedula()));
            }
        } else if (chooseEspec.getSelectedItem().toString().equalsIgnoreCase("Mecanica de motos")) {
            ident.removeAllItems();
            for (int i = 0; i < Mecanicos.getMecMotos().size(); i++) {
                ident.addItem(String.valueOf(Mecanicos.getMecMotos().get(i).getCedula()));
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chooseEspec;
    private javax.swing.JComboBox<String> ident;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel labelFinal;
    // End of variables declaration//GEN-END:variables
}
